enabled: true
left_footer: "#### © 2018 COPYRIGHT JOHN JURC\r\n\r\n\r\n\r\n"
blog_thumbnail_width: 600
blog_thumbnail_height: 450
favicon:
  user/themes/mache/images/favicon.ico:
    name: favicon.ico
    type: image/x-icon
    size: 318
    path: user/themes/mache/images/favicon.ico
logo:
  user/themes/mache/images/fortinet2-1.png:
    name: fortinet2-1.png
    type: image/png
    size: 10030
    path: user/themes/mache/images/fortinet2-1.png
